# CMake generated Testfile for 
# Source directory: /home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/examples/socket
# Build directory: /home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/cmake-cache/examples/socket
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-socket-bound-static-routing "ns3-dev-socket-bound-static-routing-optimized")
set_tests_properties(ctest-socket-bound-static-routing PROPERTIES  WORKING_DIRECTORY "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build/examples/socket/" _BACKTRACE_TRIPLES "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/macros-and-definitions.cmake;1337;add_test;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/macros-and-definitions.cmake;1506;set_runtime_outputdirectory;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/examples/socket/CMakeLists.txt;1;build_example;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/examples/socket/CMakeLists.txt;0;")
add_test(ctest-socket-bound-tcp-static-routing "ns3-dev-socket-bound-tcp-static-routing-optimized")
set_tests_properties(ctest-socket-bound-tcp-static-routing PROPERTIES  WORKING_DIRECTORY "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build/examples/socket/" _BACKTRACE_TRIPLES "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/macros-and-definitions.cmake;1337;add_test;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/macros-and-definitions.cmake;1506;set_runtime_outputdirectory;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/examples/socket/CMakeLists.txt;11;build_example;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/examples/socket/CMakeLists.txt;0;")
add_test(ctest-socket-options-ipv4 "ns3-dev-socket-options-ipv4-optimized")
set_tests_properties(ctest-socket-options-ipv4 PROPERTIES  WORKING_DIRECTORY "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build/examples/socket/" _BACKTRACE_TRIPLES "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/macros-and-definitions.cmake;1337;add_test;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/macros-and-definitions.cmake;1506;set_runtime_outputdirectory;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/examples/socket/CMakeLists.txt;22;build_example;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/examples/socket/CMakeLists.txt;0;")
add_test(ctest-socket-options-ipv6 "ns3-dev-socket-options-ipv6-optimized")
set_tests_properties(ctest-socket-options-ipv6 PROPERTIES  WORKING_DIRECTORY "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build/examples/socket/" _BACKTRACE_TRIPLES "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/macros-and-definitions.cmake;1337;add_test;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/macros-and-definitions.cmake;1506;set_runtime_outputdirectory;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/examples/socket/CMakeLists.txt;32;build_example;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/examples/socket/CMakeLists.txt;0;")
