# CMake generated Testfile for 
# Source directory: /home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/spectrum/examples
# Build directory: /home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/cmake-cache/src/spectrum/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-adhoc-aloha-ideal-phy "ns3-dev-adhoc-aloha-ideal-phy-optimized")
set_tests_properties(ctest-adhoc-aloha-ideal-phy PROPERTIES  WORKING_DIRECTORY "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build/src/spectrum/examples/" _BACKTRACE_TRIPLES "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/macros-and-definitions.cmake;1337;add_test;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/spectrum/examples/CMakeLists.txt;1;build_lib_example;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/spectrum/examples/CMakeLists.txt;0;")
add_test(ctest-adhoc-aloha-ideal-phy-matrix-propagation-loss-model "ns3-dev-adhoc-aloha-ideal-phy-matrix-propagation-loss-model-optimized")
set_tests_properties(ctest-adhoc-aloha-ideal-phy-matrix-propagation-loss-model PROPERTIES  WORKING_DIRECTORY "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build/src/spectrum/examples/" _BACKTRACE_TRIPLES "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/macros-and-definitions.cmake;1337;add_test;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/spectrum/examples/CMakeLists.txt;11;build_lib_example;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/spectrum/examples/CMakeLists.txt;0;")
add_test(ctest-adhoc-aloha-ideal-phy-with-microwave-oven "ns3-dev-adhoc-aloha-ideal-phy-with-microwave-oven-optimized")
set_tests_properties(ctest-adhoc-aloha-ideal-phy-with-microwave-oven PROPERTIES  WORKING_DIRECTORY "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build/src/spectrum/examples/" _BACKTRACE_TRIPLES "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/macros-and-definitions.cmake;1337;add_test;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/spectrum/examples/CMakeLists.txt;21;build_lib_example;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/spectrum/examples/CMakeLists.txt;0;")
add_test(ctest-tv-trans-example "ns3-dev-tv-trans-example-optimized")
set_tests_properties(ctest-tv-trans-example PROPERTIES  WORKING_DIRECTORY "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build/src/spectrum/examples/" _BACKTRACE_TRIPLES "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/macros-and-definitions.cmake;1337;add_test;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/spectrum/examples/CMakeLists.txt;31;build_lib_example;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/spectrum/examples/CMakeLists.txt;0;")
add_test(ctest-tv-trans-regional-example "ns3-dev-tv-trans-regional-example-optimized")
set_tests_properties(ctest-tv-trans-regional-example PROPERTIES  WORKING_DIRECTORY "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build/src/spectrum/examples/" _BACKTRACE_TRIPLES "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/macros-and-definitions.cmake;1337;add_test;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/spectrum/examples/CMakeLists.txt;40;build_lib_example;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/spectrum/examples/CMakeLists.txt;0;")
add_test(ctest-three-gpp-channel-example "ns3-dev-three-gpp-channel-example-optimized")
set_tests_properties(ctest-three-gpp-channel-example PROPERTIES  WORKING_DIRECTORY "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build/src/spectrum/examples/" _BACKTRACE_TRIPLES "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/macros-and-definitions.cmake;1337;add_test;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/spectrum/examples/CMakeLists.txt;49;build_lib_example;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/spectrum/examples/CMakeLists.txt;0;")
