# CMake generated Testfile for 
# Source directory: /home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/mobility/examples
# Build directory: /home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/cmake-cache/src/mobility/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-bonnmotion-ns2-example "ns3-dev-bonnmotion-ns2-example-optimized")
set_tests_properties(ctest-bonnmotion-ns2-example PROPERTIES  WORKING_DIRECTORY "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build/src/mobility/examples/" _BACKTRACE_TRIPLES "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/macros-and-definitions.cmake;1337;add_test;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/mobility/examples/CMakeLists.txt;11;build_lib_example;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/mobility/examples/CMakeLists.txt;0;")
add_test(ctest-main-random-topology "ns3-dev-main-random-topology-optimized")
set_tests_properties(ctest-main-random-topology PROPERTIES  WORKING_DIRECTORY "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build/src/mobility/examples/" _BACKTRACE_TRIPLES "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/macros-and-definitions.cmake;1337;add_test;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/mobility/examples/CMakeLists.txt;11;build_lib_example;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/mobility/examples/CMakeLists.txt;0;")
add_test(ctest-main-random-walk "ns3-dev-main-random-walk-optimized")
set_tests_properties(ctest-main-random-walk PROPERTIES  WORKING_DIRECTORY "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build/src/mobility/examples/" _BACKTRACE_TRIPLES "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/macros-and-definitions.cmake;1337;add_test;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/mobility/examples/CMakeLists.txt;11;build_lib_example;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/mobility/examples/CMakeLists.txt;0;")
add_test(ctest-ns2-mobility-trace "ns3-dev-ns2-mobility-trace-optimized")
set_tests_properties(ctest-ns2-mobility-trace PROPERTIES  WORKING_DIRECTORY "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build/src/mobility/examples/" _BACKTRACE_TRIPLES "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/macros-and-definitions.cmake;1337;add_test;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/mobility/examples/CMakeLists.txt;11;build_lib_example;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/mobility/examples/CMakeLists.txt;0;")
add_test(ctest-main-grid-topology "ns3-dev-main-grid-topology-optimized")
set_tests_properties(ctest-main-grid-topology PROPERTIES  WORKING_DIRECTORY "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build/src/mobility/examples/" _BACKTRACE_TRIPLES "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/macros-and-definitions.cmake;1337;add_test;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/mobility/examples/CMakeLists.txt;19;build_lib_example;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/mobility/examples/CMakeLists.txt;0;")
add_test(ctest-mobility-trace-example "ns3-dev-mobility-trace-example-optimized")
set_tests_properties(ctest-mobility-trace-example PROPERTIES  WORKING_DIRECTORY "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build/src/mobility/examples/" _BACKTRACE_TRIPLES "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/macros-and-definitions.cmake;1337;add_test;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/mobility/examples/CMakeLists.txt;28;build_lib_example;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/mobility/examples/CMakeLists.txt;0;")
add_test(ctest-reference-point-group-mobility-example "ns3-dev-reference-point-group-mobility-example-optimized")
set_tests_properties(ctest-reference-point-group-mobility-example PROPERTIES  WORKING_DIRECTORY "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build/src/mobility/examples/" _BACKTRACE_TRIPLES "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/macros-and-definitions.cmake;1337;add_test;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/mobility/examples/CMakeLists.txt;37;build_lib_example;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/mobility/examples/CMakeLists.txt;0;")
