# CMake generated Testfile for 
# Source directory: /home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/netanim/examples
# Build directory: /home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/cmake-cache/src/netanim/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-dumbbell-animation "ns3-dev-dumbbell-animation-optimized")
set_tests_properties(ctest-dumbbell-animation PROPERTIES  WORKING_DIRECTORY "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/macros-and-definitions.cmake;1337;add_test;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/netanim/examples/CMakeLists.txt;13;build_lib_example;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-grid-animation "ns3-dev-grid-animation-optimized")
set_tests_properties(ctest-grid-animation PROPERTIES  WORKING_DIRECTORY "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/macros-and-definitions.cmake;1337;add_test;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/netanim/examples/CMakeLists.txt;13;build_lib_example;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-star-animation "ns3-dev-star-animation-optimized")
set_tests_properties(ctest-star-animation PROPERTIES  WORKING_DIRECTORY "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/macros-and-definitions.cmake;1337;add_test;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/netanim/examples/CMakeLists.txt;13;build_lib_example;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-colors-link-description "ns3-dev-colors-link-description-optimized")
set_tests_properties(ctest-colors-link-description PROPERTIES  WORKING_DIRECTORY "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/macros-and-definitions.cmake;1337;add_test;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/netanim/examples/CMakeLists.txt;13;build_lib_example;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-resources-counters "ns3-dev-resources-counters-optimized")
set_tests_properties(ctest-resources-counters PROPERTIES  WORKING_DIRECTORY "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/macros-and-definitions.cmake;1337;add_test;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/netanim/examples/CMakeLists.txt;13;build_lib_example;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-wireless-animation "ns3-dev-wireless-animation-optimized")
set_tests_properties(ctest-wireless-animation PROPERTIES  WORKING_DIRECTORY "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/macros-and-definitions.cmake;1337;add_test;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/netanim/examples/CMakeLists.txt;23;build_lib_example;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-uan-animation "ns3-dev-uan-animation-optimized")
set_tests_properties(ctest-uan-animation PROPERTIES  WORKING_DIRECTORY "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/macros-and-definitions.cmake;1337;add_test;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/netanim/examples/CMakeLists.txt;36;build_lib_example;/home/vaishnavi/project/V2I_WorkingVersion1.3/ms-van3t/ns-3-dev/src/netanim/examples/CMakeLists.txt;0;")
